"""add family achievement daily_task

Revision ID: 092530545603
Revises: 
Create Date: 2026-04-09 17:25:51.031133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092530545603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cognitive_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('memory_score', sa.Float(), nullable=True, comment='记忆力基线分数'),
    sa.Column('attention_score', sa.Float(), nullable=True, comment='注意力基线分数'),
    sa.Column('calculation_score', sa.Float(), nullable=True, comment='计算力基线分数'),
    sa.Column('logic_score', sa.Float(), nullable=True, comment='逻辑推理基线分数'),
    sa.Column('language_score', sa.Float(), nullable=True, comment='语言能力基线分数'),
    sa.Column('spatial_score', sa.Float(), nullable=True, comment='空间定向基线分数'),
    sa.Column('face_score', sa.Float(), nullable=True, comment='人脸识别基线分数'),
    sa.Column('rhythm_score', sa.Float(), nullable=True, comment='节律训练基线分数'),
    sa.Column('classification_score', sa.Float(), nullable=True, comment='分类归纳基线分数'),
    sa.Column('dual_task_score', sa.Float(), nullable=True, comment='双重任务基线分数'),
    sa.Column('total_score', sa.Float(), nullable=True, comment='综合基线分数'),
    sa.Column('assessment_type', sa.String(length=20), nullable=True, comment='评估类型: initial/periodic'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='评估时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_baselines_id'), 'cognitive_baselines', ['id'], unique=False)
    op.create_index(op.f('ix_cognitive_baselines_user_id'), 'cognitive_baselines', ['user_id'], unique=False)
    op.create_table('daily_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('task_date', sa.String(length=10), nullable=False, comment='任务日期 YYYY-MM-DD'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型'),
    sa.Column('task_desc', sa.String(length=200), nullable=False, comment='任务描述'),
    sa.Column('target_value', sa.Integer(), nullable=True, comment='目标值'),
    sa.Column('current_value', sa.Integer(), nullable=True, comment='当前进度'),
    sa.Column('is_completed', sa.Integer(), nullable=True, comment='是否完成(0否1是)'),
    sa.Column('reward_points', sa.Integer(), nullable=True, comment='奖励积分'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_tasks_id'), 'daily_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_task_date'), 'daily_tasks', ['task_date'], unique=False)
    op.create_index(op.f('ix_daily_tasks_user_id'), 'daily_tasks', ['user_id'], unique=False)
    op.create_table('family_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watcher_id', sa.Integer(), nullable=False, comment='关注者ID(子女)'),
    sa.Column('watched_id', sa.Integer(), nullable=False, comment='被关注者ID(父母)'),
    sa.Column('relation_type', sa.Enum('child', 'spouse', 'caregiver', 'other'), nullable=True, comment='关系类型'),
    sa.Column('invite_code', sa.String(length=20), nullable=True, comment='邀请码'),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'unbound'), nullable=True, comment='状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['watched_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['watcher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index(op.f('ix_family_relations_id'), 'family_relations', ['id'], unique=False)
    op.create_index(op.f('ix_family_relations_watched_id'), 'family_relations', ['watched_id'], unique=False)
    op.create_index(op.f('ix_family_relations_watcher_id'), 'family_relations', ['watcher_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('achievement_key', sa.String(length=50), nullable=False, comment='成就标识'),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True, comment='解锁时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_key'), 'user_achievements', ['achievement_key'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.add_column('training_records', sa.Column('is_practice', sa.Integer(), nullable=False, comment='是否练习模式(0否1是)'))
    op.add_column('users', sa.Column('font_size', sa.String(length=10), nullable=True, comment='字体大小: normal/large/xlarge'))
    op.add_column('users', sa.Column('high_contrast', sa.Integer(), nullable=True, comment='高对比度模式(0关1开)'))
    op.add_column('users', sa.Column('reminder_time', sa.String(length=10), nullable=True, comment='每日提醒时间 HH:MM'))
    op.add_column('users', sa.Column('baseline_completed', sa.Integer(), nullable=True, comment='是否完成基线评估(0否1是)'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'baseline_completed')
    op.drop_column('users', 'reminder_time')
    op.drop_column('users', 'high_contrast')
    op.drop_column('users', 'font_size')
    op.drop_column('training_records', 'is_practice')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_key'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_family_relations_watcher_id'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_watched_id'), table_name='family_relations')
    op.drop_index(op.f('ix_family_relations_id'), table_name='family_relations')
    op.drop_table('family_relations')
    op.drop_index(op.f('ix_daily_tasks_user_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_task_date'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_id'), table_name='daily_tasks')
    op.drop_table('daily_tasks')
    op.drop_index(op.f('ix_cognitive_baselines_user_id'), table_name='cognitive_baselines')
    op.drop_index(op.f('ix_cognitive_baselines_id'), table_name='cognitive_baselines')
    op.drop_table('cognitive_baselines')
    # ### end Alembic commands ###